language: java
sudo: false # faster builds

env:
  global:
    - secure: "rKT8QWcOvYxCcyChF0sFqppRT7zadIHMZgHwBXOAeRdCRGiG2KxqflkG2WAaTOjei99SZXvtWBmZbWcfxLOCp2Je6szqL14rlSB9VK2uvw3ipGqm2KEbT+gRvQagXvYEJtZo40lXZEZGcuTO6hACl5PFryBjKG+7nr+jv8VeB/pPQHdAsATylxGUFXNROOBJ4ia8ATQZozBHFNflDpPE0MYinIGIN7af2xrz8S9TVdmV3rXMkHf2R6A5v5WNm2JGnBsyzoGATUA3O5YNwXMiqBf07YR95K6UEtLlBWC/qsU1aSQfPTDpVOf6dydbpejVC0asE2IYcEUFLTt0FYB8ydu5jFSc9aCqmTxpVpqd0/ZPJwV79LyZEygUO2F10ZbcJhGLIkA5BA94wK9ZKiONC3/Xr/sn1ZUJLWDLlWdHPioTCvxpsSUWoFMRByGC8kG8GiEQWPpPp3szkxpS4jx109rvPuMVHC1/Q7FPCaIgD+qcgagfChOvjtV1U8smauaz90eOnyLSh4h2fQW/thjsD2dJjNdvrYLvrRBdv87S72uio4m36kAjlLIxOMQwGShA3CahIOKAlKg3DWtGeMrS+Br1uoUoG7+fGeby07VjIv6Bwi3WV4QaU7tMAVi7eYDpwhOHfs3Sj4ubecpgWvGEf3zkKzYHDJu/5mXrkCEXcHI="
    - secure: "1UORzOa6scVL+bo4jKaRxEwYNAABcyRYHKnuLsHZRxh+4BLfcIp9XkMjp9rc7xLHL5KKXNZHyHjDe34rqoTmepETbZ7WE74r3SdHm+MhbTjsKoucEio4Tqys5oJjRlypcBm7oRAN0ddyn00eXFEVv2ihaOMZjctXGb/F8vYxY0b/CxlWbaj0myUH23NyJbtjQ6ouliU2DqBmxerE5K054Zsvei8HXLSVkqFaCpsUisbNZWpNCYi2Al0YFm36EeKdnmY7xL8dfrSnMVJakcS3D/yDj+FpuS3O8M7dGtzO/CbRKkX14hJAFHkYwyrtJAeFrQqMug2sYVDaXPvoAAGteYd8fasic6s0RnnJUS4K/ftaWRPMykVAQ9LT8oDBJ5SuFPKsr1jhu5vtDA4j+jIWkV1keefMxqgsHwa8L2i9ZWD5D5rOnEZq33NSVSA8vz8Z0mvArC74updjmhvFVDsKzrbn+Fb+cjotV8EO6U0x3hTdTLlpKd2T98w6+4qzVuXFvdSJBgapKbhvhuZwW8YEfG6toKldmpOy6CP/HRDkIEVG6tjO7bfWycr8TnwVe9KiH+z3IwM6YkcYDIWSgRexgC4E/3bPG3cmXwGPd+jzwiGZAu7/h0Il2+jRg+c/o4Xo23y4RCJxxDSYl3490DCyIb4QvDlZsexOhKPXFvmCQzo="


before_install:
  - nvm install stable                       # To install npm
  - sudo apt-get install jq                  # For Codacy
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)


install:
  - npm install
  - gradle cucumberReportInstall

script:
  - gradle check
  - gradle clean build

after_script:
  - gradle test jacocoTestReport
  - gradle cucumberReport

after_success:
  - bash <(curl -s https://codecov.io/bash)   # For Codecov.io
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Java -r build/reports/jacoco/test/jacocoTestReport.xml   # Codacy coverage