language: java
sudo: false # faster builds

before_install:
  - "nvm install stable"

install:
  - "npm install"
  - "gradle cucumberReportInstall"

before_script:
  - "echo ------ before ------"
  - "pwd"
  - "echo --------------------"

script:
  - "echo success!"
  - "echo ------ script ------"
  - "pwd"
  - "echo --------------------"

after_script:
  - "echo ------ after  ------"
  - "pwd"
  - "echo --------------------"

